### ISSUE TITLE
Bug1

### ISSUE THREAD

**Issue by nadiababak** [egrig/training-PigGame-eg#5]
1. Run  the Pig game. 
2. We press  Roll dice.
3. The player 1 starts the game and rolls a dice.
4. We see that player, did not throw the dice when you press a button Roll dice.
5. The turn goes to the next player.

**Comment by nadiababak** [comment]
https://share.vidyard.com/watch/B4x1phumcDKUmTxDnerWGA?autoplay=1

**Comment by egrig** [comment]
The issue is around the first player losing their turn because of a dice roll ( = 1). The game quickly switches the player's turn without showing the above dice roll. So the change in player's turn is done without displaying a dice =1, and thus it isn't clear why the game switched players.

**Comment by egrig** [comment]
The fix will display the rolled dice BEFORE the player switch to make it clear that the switch occured due to one of the dice roloing to a 1.

**Comment by egrig** [comment]
@nadiababak code was fixed to display the dice=1 when players switch.

**Comment by egrig** [comment]
Please download updated code and retest.
